# Generated by Django 3.0.6 on 2026-05-19 15:20

from django.db import migrations, models
import django.db.models.deletion


def create_default_categories(apps, schema_editor):
    Category = apps.get_model('pybo', 'Category')
    Question = apps.get_model('pybo', 'Question')
    defaults = [
        ('django', 'Django', 'Django framework questions'),
        ('python', 'Python', 'Python language questions'),
        ('error', 'Error', 'Debugging and troubleshooting'),
        ('notice', 'Notice', 'Announcements'),
        ('free', 'Free', 'General discussion'),
    ]
    free_category = None
    for slug, name, description in defaults:
        category, _ = Category.objects.get_or_create(
            slug=slug,
            defaults={'name': name, 'description': description},
        )
        if slug == 'free':
            free_category = category
    if free_category:
        Question.objects.filter(category__isnull=True).update(category=free_category)


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20200507_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('description', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybo.Category'),
        ),
        migrations.RunPython(create_default_categories, migrations.RunPython.noop),
    ]
