# Generated by Django 3.0.6 on 2026-05-19 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0008_gallery_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bookmark_users',
            field=models.ManyToManyField(blank=True, related_name='bookmark_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
